### ISSUE TITLE
Upload fails

### ISSUE THREAD

**Issue by Pr0xy671** [sweetsoftware/Ares#15]
I specify the file path when I do the command: "upload C:/Users/Prox/Desktop/image.jpg"
But I get this error in the server:

```
[14/Aug/2016:00:00:10] HTTP
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Python27\lib\site-packages\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Python27\lib\site-packages\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Users\Prox\Desktop\server\server.py", line 289, in upload
    outfile = open(save_path, 'wb')
IOError: [Errno 2] No such file or directory: u'uploads\\DESKTOP-GS3T472\\image.jpg'
```

Can you point me in the right direction?

**Comment by Mangodzilla** [comment]
Tryed "upload C:\Users\Prox\Desktop\image.jpg" ? (reversed slashes \/)

**Comment by Pr0xy671** [comment]
Yeah, I tried:
```
upload C:\Users\Prox\Desktop\image.jpg
upload C:\\Users\\Prox\\Desktop\\image.jpg
upload `C:/Users/Prox/Desktop/image.jpg
```
I get the same IOError

I even tried putting quotation marks:
```
upload "C:/Users/Prox/Desktop/image.jpg"
upload "C:\Users\Prox\Desktop\image.jpg"
```
I didn't get errors, but the file is not in the ares/server/upload folder.

**Comment by knil92** [comment]
I thought the upload command was to upload files to the zombie? and the download command was to download files from a zombie?

**Comment by Pr0xy671** [comment]
Nope, the download command makes the zombie download the file, and the upload command is supposed to make the zombie upload a file from its drive to your harddrive.

**Comment by knil92** [comment]
to be fair though, there really isnt a need for a download command as you can just use bitsadmin command to download files

**Comment by Pr0xy671** [comment]
Ohh, interesting. Can you use bitsadmin to upload files as well? I'm not familiar with bitsadmin.

**Comment by knil92** [comment]
I dont think you can, but the bitsadmin command uses direct download links to download files. So when you go to the link in your browser and it pops up asking if you want to run or save, thats the url you need. im not 100% sure on it, but i think the syntax is something like bitsadmin https:\\download.url "C:\destination folder" Just google using bitsadmin to download files and there should be a few links. Its funny because the day that i found that bitsadmin command, i told my friend about it and he was literally fixing a computer that had a virus that was using it to download other stuff XD. I was thinking that you could make a batchfile with bitsadmin commands, to download and run the agent, and then convert the bat file into an exe file. When i did that, i think only 1 or 2 virus scanners detected it on totalvirus.

**Comment by Pr0xy671** [comment]
@knil92, Thanks for the help man. Figured out an alternative. I though of uploading the file to a webhosting website like filedropper, etc. then returning the download link. Something like: 
```utils.send_output(download_link)```
